name: YuruCra
version: 0.0.1
main: com.github.kotyabuchi.YuruCra.Main
author: kotyabuchi
api-version: '1.20'
commands:
  menu:
    usage: /<command>
  home:
    usage: /<command>
  itemedit:
    usage: /<command> player damage <value>
  playermanager:
    aliases: [pm]
